trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "14.x"
    displayName: "Install Node.js"

  - script: |
      npm install
    displayName: "Installation"

  - script: |
      npm run lint
    displayName: "Linting"
    
  - script: |
      npm run build
    displayName: "Build"
      
  - script: |
      npm run test
    displayName: "Tests"
